spring:
  application:
    name: order-service

server:
  port: 8081

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serverviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost